# Site settings
title: Vernilac - Think Differently
email: parageos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  VERNILAC S.A. is one of the largest producers of paints & varnishes in GREECE and its trademark is identified with high quality products.
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

exclude:
  - bower_components
  - bower.json
  - README.md
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir:  bower_components/uikit/scss
  style:     :compressed

collections:
  acrylics:
    output: true
  emulsions:
    output: true
  primers:
    output: true
  woods:
    output: true
  wood-primers:
    output: true
  metals: 
    output: true
  metal-primers: 
    output: true